### PR TITLE
Create Working

### PR DESCRIPTION
**Pull request by kjjjjjjjjjjjj**

### CODE REVIEW

**Comment by aaaapai** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/pull/5096
Is this valid code?

**Comment by kjjjjjjjjjjjj** [comment]
yes or no

**Comment by kjjjjjjjjjjjj** [comment]
I mean yeah is it

**Comment by aaaapai** [comment]
> I mean yeah is it

How do you prove that it works?

**Comment by kjjjjjjjjjjjj** [comment]
Please build me internal 17 for my  pojavauncher
and 8

**Comment by kjjjjjjjjjjjj** [comment]
And please you and me build a launcher like HMCL-PE which support lower versions of Android just you and me

**Comment by aaaapai** [comment]
> And please you and me build a launcher like HMCL-PE which support lower versions of Android just you and me

The official versions of HMCL-pe and FCL support Android 8+, while the PojavLauncher supports Android 5+. HMCL-PE has been officially declared out of maintenance, meaning it is obsolete and there is no need to build

**Comment by kjjjjjjjjjjjj** [comment]
pojav Launcher  new repository so can we start it a repository like this I want to work with you including my coding experience

**Pull request closed without merging**
